---
sudo: false
language: generic
rvm:
  - 2.2

install:
  # Install gems
  - bundle install

script:
  # Validate README.md URLs
  - awesome_bot
      --allow-timeout
      --request-delay 1
      --skip-save-results
      --allow-dupe
      --white-list=localhost
      --files $(find . -name "*.md" | tr '\n' ',')
