FROM mesaguy/fedora-25-kitchen-base-x86_64:latest

# Clean (purge) the repo cache
RUN dnf -y clean all && \
# Install python 2.7
dnf -y install python && \
# Clean (purge) the repo cache
dnf -y clean all && rm -rf /var/cache/dnf/* /var/cache/yum/* && \
# Purge logs
rm -rf /var/log/* /var/run/log/journal

# Add your specific Ansible SSH public key. This only works when run via
# kitchen, when run with the following options in your .kitchen.yml file:
#
#    driver_config:
#      build_options:
#        build-arg: SSH_KEY=<%= File.read('.kitchen/docker_id_rsa.pub') %>
#
ARG SSH_KEY
RUN echo "$SSH_KEY" >> /home/kitchen/.ssh/authorized_keys

# Image metadata
LABEL org.label-schema.vendor="MesaGuy" \
      org.label-schema.name="Fedora Linux 25 kitchen-ansible" \
      org.label-schema.description="Image boots Fedora Linux 25 via systemd configured for kitchen ansible testing" \
      com.mesaguy.operatingsystem.eol="true"
