FROM mesaguy/centos-6.10-kitchen-base-x86_64:latest

# Make a file to force new layer
RUN touch /root/ANSIBLE && \
# Purge logs
rm -rf /var/log/*

# Image metadata
LABEL org.label-schema.vendor="MesaGuy" \
      org.label-schema.name="CentOS Linux 6.10 kitchen-ansible" \
      org.label-schema.description="Image boots CentOS Linux 6.10 via SysV init configured for kitchen ansible testing" \
      com.mesaguy.operatingsystem.eol="false"
