FROM mesaguy/fedora-20-kitchen-base-x86_64:latest

# Make a file to force new layer
RUN touch /root/ANSIBLE && \
# Purge logs
rm -rf /var/log/* /var/run/log/journal

# Add your specific Ansible SSH public key. This only works when run via
# kitchen, when run with the following options in your .kitchen.yml file:
#
#    driver_config:
#      build_options:
#        build-arg: SSH_KEY=<%= File.read('.kitchen/docker_id_rsa.pub') %>
#
ARG SSH_KEY
RUN echo "$SSH_KEY" >> /home/kitchen/.ssh/authorized_keys && \
chmod 0600 /home/kitchen/.ssh/authorized_keys

# Image metadata
LABEL org.label-schema.vendor="MesaGuy" \
      org.label-schema.name="Fedora Linux 20 (Heisenbug) kitchen-ansible" \
      org.label-schema.description="Image boots Fedora Linux 20 (Heisenbug) via systemd configured for kitchen ansible testing" \
      com.mesaguy.operatingsystem.eol="true"
