FROM mesaguy/gentoo-systemd-boot-x86_64:latest

# Sync portage
RUN mkdir -p /usr/portage/distfiles /usr/portage/metadata /usr/portage/packages && \
chown -R portage:portage /usr/portage && \
emerge-webrsync && \
# Install sudo and openssh for kitchen
emerge app-admin/sudo net-misc/openssh && \
# Cleanup portage, downloaded source files and compile directories
rm -rf /usr/portage /var/tmp/* && \
# Purge logs
rm -rf /var/log/*

# Adjust sshd defaults per kitchen's needs
RUN test -f /usr/lib64/misc/sftp-server && \
printf "Subsystem sftp /usr/lib64/misc/sftp-server\\nUseDNS no\\nUsePAM no\\nPasswordAuthentication yes\\nUsePrivilegeSeparation no\\n" > /etc/ssh/sshd_config && \
# Start SSH on boot
systemctl enable sshd && \
# Add 'kitchen' user
if ! getent passwd kitchen; then useradd -d /home/kitchen -m -s /bin/bash -p '*' kitchen; fi && \
# Allow unlimited sudo privileges to 'kitchen' user
echo "kitchen ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers && echo "Defaults !requiretty" >> /etc/sudoers && \
# Make 'kitchen' user's authorized_keys file (empty)
touch /home/kitchen/.ssh/authorized_keys && \
# Secure 'kitchen' user's authorized_keys file
chmod 0600 /home/kitchen/.ssh/authorized_keys && \
# Fix 'kitchen' user's SSH directory permissions
chown -R kitchen:kitchen /home/kitchen/.ssh

# Expose SSH
EXPOSE 22

# Image metadata
LABEL org.label-schema.vendor="Mesaguy" \
      org.label-schema.name="Gentoo Linux systemd latest rolling-release kitchen-ansible" \
      org.label-schema.description="Image boots Gentoo Linux's latest rolling-release via systemd configured for kitchen ansible testing" \
      com.mesaguy.operatingsystem.eol="false"
