FROM mesaguy/ubuntu-17.10-kitchen-base-x86_64:latest

# Update repo definitions
RUN apt update && \
# Install python for ansible
apt install -y python && \
# Clean (purge) the repo cache
apt-get clean && \
rm -rf /var/lib/apt/lists/* && \
# Purge logs
rm -rf /var/log/*

# Image metadata
LABEL org.label-schema.vendor="MesaGuy" \
      org.label-schema.name="Ubuntu Linux 17.10 (Artful Aardvark) kitchen-ansible" \
      org.label-schema.description="Image boots Ubuntu Linux 17.10 (Artful Aardvark) via systemd configured for kitchen ansible testing" \
      com.mesaguy.operatingsystem.eol="false"
