FROM mesaguy/gentoo-openrc-kitchen-base-x86_64:latest

# Make a file to force new layer
RUN touch /root/ANSIBLE && \
# Purge logs
rm -rf /var/log/*

# Image metadata
LABEL org.label-schema.vendor="MesaGuy" \
      org.label-schema.name="Gentoo Linux systemd latest rolling-release kitchen-ansible" \
      org.label-schema.description="Image boots Gentoo Linux's latest rolling-release via systemd configured for kitchen ansible testing" \
      com.mesaguy.operatingsystem.eol="false"
