FROM mesaguy/oraclelinux-6.9-kitchen-base-x86_64:latest

# This Dockerfile RUN fixes problems with Ansible in relation to downloading files
# from https sites.
# Install EPEL for python-pip
RUN yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm && \
# Install pip along with libraries needed to install Python OpenSSL libraries
yum install -y pyOpenSSL python-pip python-devel libffi-devel openssl-devel && \
# Install Python OpenSSL libraries
pip install urllib3 pyopenssl ndg-httpsclient pyasn1

# Image metadata
LABEL org.label-schema.vendor="Mesaguy" \
      org.label-schema.name="Oracle Linux Linux 6.9 kitchen-ansible" \
      org.label-schema.description="Image boots Oracle Linux Linux 6.9 via SysV init configured for kitchen ansible testing" \
      com.mesaguy.operatingsystem.eol="true"
