FROM mesaguy/oraclelinux-6.10-kitchen-base-x86_64:latest

# This Dockerfile RUN fixes problems with Ansible in relation to downloading files
# from https sites.
# Install EPEL for python-pip
RUN yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm && \
# Install pip along with libraries needed to install Python OpenSSL libraries
yum install -y python-pip python-devel libffi-devel openssl-devel && \
# Install Python OpenSSL libraries
pip install urllib3 pyopenssl ndg-httpsclient pyasn1

# Add your specific Ansible SSH public key. This only works when run via
# kitchen, when run with the following options in your .kitchen.yml file:
#
#    driver_config:
#      build_options:
#        build-arg: SSH_KEY=<%= File.read('.kitchen/docker_id_rsa.pub') %>
#
ARG SSH_KEY
RUN echo "$SSH_KEY" >> /home/kitchen/.ssh/authorized_keys

# Image metadata
LABEL org.label-schema.vendor="MesaGuy" \
      org.label-schema.name="Oracle Linux Linux 6.10 kitchen-ansible" \
      org.label-schema.description="Image boots Oracle Linux Linux 6.10 via SysV init configured for kitchen ansible testing" \
      com.mesaguy.operatingsystem.eol="false"
