FROM mesaguy/ubuntu-14.04-kitchen-base-x86_64:latest

# Make a file to force new layer
RUN touch /root/ANSIBLE && \
# Purge logs
rm -rf /var/log/*

# Image metadata
LABEL org.label-schema.vendor="MesaGuy" \
      org.label-schema.name="Ubuntu Linux 14.04 (Trusty Tahr) kitchen-ansible" \
      org.label-schema.description="Image boots Ubuntu Linux 14.04 (Trusty Tahr) via Upstart configured for kitchen ansible testing" \
      com.mesaguy.operatingsystem.eol="false"
