FROM mesaguy/alpine-3.2-kitchen-base-x86_64:latest

# Add edge community repository (for shadow)
RUN echo http://dl-2.alpinelinux.org/alpine/edge/community/ >> /etc/apk/repositories && \
# Install python and shadow (user and group management)
apk add --no-cache python shadow && \
# Purge logs
rm -rf /var/log/*

# Image metadata
LABEL org.label-schema.vendor="Mesaguy" \
      org.label-schema.name="Alpine Linux 3.2 kitchen-ansible" \
      org.label-schema.description="Image boots Alpine Linux 3.2 via OpenRC configured for kitchen ansible testing" \
      com.mesaguy.operatingsystem.eol="true"
