FROM mesaguy/fedora-26-kitchen-base-x86_64:latest

# Add your specific Ansible SSH public key. This only works when run via
# kitchen, when run with the following options in your .kitchen.yml file:
#
#    driver_config:
#      build_options:
#        build-arg: SSH_KEY=<%= File.read('.kitchen/docker_id_rsa.pub') %>
#
ARG SSH_KEY
RUN echo "$SSH_KEY" >> /home/kitchen/.ssh/authorized_keys

# Image metadata
LABEL org.label-schema.vendor="MesaGuy" \
      org.label-schema.name="Fedora Linux 26 kitchen-ansible" \
      org.label-schema.description="Image boots Fedora Linux 26 via systemd configured for kitchen ansible testing" \
      com.mesaguy.operatingsystem.eol="true"
