FROM mesaguy/debian-7-kitchen-base-x86_64:latest

# Update repo definitions
RUN apt-get update && \
# Install python for ansible
apt-get install --no-install-recommends -y python && \
# Clean (purge) the repo cache
apt-get clean && \
rm -rf /var/lib/apt/lists/* && \
# Purge logs
rm -rf /var/log/*

# Image metadata
LABEL org.label-schema.vendor="Mesaguy" \
      org.label-schema.name="Debian Linux 7 (Wheezy) kitchen-ansible" \
      org.label-schema.description="Image boots Debian Linux 7 (Wheezy) via Upstart configured for kitchen ansible testing" \
      com.mesaguy.operatingsystem.eol="true"
