FROM mesaguy/centos-5.11-kitchen-base-x86_64:latest

# https://www.ansible.com/blog/using-ansible-to-manage-rhel-5-yesterday-today-and-tomorrow

# Clean (purge) the repo cache
RUN yum -d1 -y clean all && \
# Update all packages
yum -d1 -y update && \
# Install EPEL GPG key
wget https://archives.fedoraproject.org/pub/archive/epel/RPM-GPG-KEY-EPEL-5 && \
sudo rpm --import RPM-GPG-KEY-EPEL-5 && \
rm -f RPM-GPG-KEY-EPEL-5 && \
# Install EPEL repository for Python 2.6
rpm -ihv http://archives.fedoraproject.org/pub/archive/epel/5/x86_64/epel-release-5-4.noarch.rpm && \
# Install python 2.6
yum -y install python26 && \
# Clean (purge) the repo cache
yum -d1 -y clean all && rm -rf /var/cache/yum/* && \
# Purge logs
rm -rf /var/log/*

# Image metadata
LABEL org.label-schema.vendor="MesaGuy" \
      org.label-schema.name="CentOS Linux 5.11 kitchen-ansible" \
      org.label-schema.description="Image boots CentOS Linux 5.11 via SysV init configured for kitchen ansible testing" \
      com.mesaguy.operatingsystem.eol="false"
