# Source (EOL)
FROM debian:7

# Disable tty's
RUN sed -iE '/[0-9]+:.*tty[0-9]+/d' /etc/inittab

# Start via init
CMD ["/sbin/init"]

# Image metadata
LABEL org.label-schema.vendor="Mesaguy" \
      org.label-schema.name="Debian Linux 7 (Wheezy) boot" \
      org.label-schema.description="Image boots Debian Linux 7 (Wheezy) via Upstart" \
      com.mesaguy.operatingsystem.eol="true"
