# Source
FROM base/archlinux:latest

# Update repo definitions
RUN pacman -Syu --noconfirm && \
# Install systemctl
pacman --noconfirm -S systemd && \
# Clean (purge) the repo cache
pacman --noconfirm -Scc && rm -rf /var/lib/pacman/sync/* && \
# Purge logs
rm -rf /var/log/* /var/run/log/journal

# Strip down systemd
RUN (cd /lib/systemd/system/sysinit.target.wants && for i in *; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; done) && \
rm -f /lib/systemd/system/multi-user.target.wants/* && \
rm -f /etc/systemd/system/*.wants/* && \
rm -f /lib/systemd/system/local-fs.target.wants/* && \
rm -f /lib/systemd/system/sockets.target.wants/*udev* && \
rm -f /lib/systemd/system/sockets.target.wants/*initctl* && \
rm -f /lib/systemd/system/basic.target.wants/* && \
rm -f /lib/systemd/system/anaconda.target.wants/*

# Without this, init won't start the enabled services. Starting the services
# fails with one of:
#     Failed to get D-Bus connection: Operation not permitted
#     System has not been booted with systemd as init system (PID 1). Can't operate.
#     Failed to connect to bus: No such file or directory
VOLUME [ "/sys/fs/cgroup", "/run" ]

# Start via systemd
CMD ["/usr/lib/systemd/systemd"]

# Image metadata
LABEL org.label-schema.vendor="MesaGuy" \
      org.label-schema.name="ArchLinux latest rolling-release boot" \
      org.label-schema.description="Image boots ArchLinux's latest rolling-release via systemd" \
      com.mesaguy.operatingsystem.eol="false"
