# Source
FROM centos:6.7

# Clean (purge) the repo cache
RUN yum -d1 -y clean all && rm -rf /var/cache/yum/* && \
# Upgrade buggy yum:
yum -d1 -y install yum-plugin-ovl || true && \
yum -d1 -y update yum && \
# Install upstart
yum -d1 -y install upstart && \
# Clean (purge) the repo cache
yum -d1 -y clean all && rm -rf /var/cache/yum/* && \
# Purge logs
rm -rf /var/log/*

# Disable all services
RUN rm -f /etc/rc.d/rc*.d/*

# Start via init
CMD ["/sbin/init"]

# Image metadata
LABEL org.label-schema.vendor="MesaGuy" \
      org.label-schema.name="CentOS Linux 6.7 boot" \
      org.label-schema.description="Image boots CentOS Linux 6.7 via SysV init" \
      com.mesaguy.operatingsystem.eol="true"
