# Source
FROM alpine:edge

# Update repository information
RUN apk update && \
# Update all packages
apk upgrade && \
# Install openrc
apk add openrc && \
# Remove caches
rm -f /var/cache/apk/* && \
# Purge logs
rm -rf /var/log/*

# Disable ttys
RUN sed -i 's/^tty/#tty/g' /etc/inittab

# Needed by OpenRC
VOLUME [ "/run" ]

# Start via init
CMD ["/sbin/init"]

# Image metadata
LABEL org.label-schema.vendor="MesaGuy" \
      org.label-schema.name="Alpine Linux edge latest rolling-release boot" \
      org.label-schema.description="Image boots Alpine Linux's latest rolling-release edge via OpenRC" \
      com.mesaguy.operatingsystem.eol="false"
