# Source (EOL)
FROM alpine:3.4

# Update repository information
RUN apk update && \
# Update all packages
apk upgrade && \
# Install openrc
apk add openrc && \
# Remove caches
rm -f /var/cache/apk/* && \
# Setup compatibility with libc
mkdir -p /lib64 && ln -s /lib/libc.musl-x86_64.so.1 /lib64/ld-linux-x86-64.so.2 && \
# Purge logs
rm -rf /var/log/*

# Disable ttys
RUN sed -i 's/^tty/#tty/g' /etc/inittab

# Needed by OpenRC
VOLUME [ "/run" ]

# Start via init
CMD ["/sbin/init"]

# Image metadata
LABEL org.label-schema.vendor="MesaGuy" \
      org.label-schema.name="Alpine Linux 3.4 boot" \
      org.label-schema.description="Image boots Alpine Linux 3.4 via OpenRC" \
      com.mesaguy.operatingsystem.eol="true"
