# Source (EOL)
FROM debian:7

# Update repo definitions
RUN apt-get update && \
# Upgrade all packages
apt-get dist-upgrade -y && \
# Clean (purge) the repo cache
apt-get clean && \
rm -rf /var/lib/apt/lists/* && \
# Purge logs
rm -rf /var/log/*

# Start via init
CMD ["/sbin/init"]

# Image metadata
LABEL org.label-schema.vendor="MesaGuy" \
      org.label-schema.name="Debian Linux 7 (Wheezy) boot" \
      org.label-schema.description="Image boots Debian Linux 7 (Wheezy) via Upstart" \
      com.mesaguy.operatingsystem.eol="true"
