# Source
FROM oraclelinux:6.7

# Clean (purge) the repo cache
RUN yum -d1 -y clean all && rm -rf /var/cache/yum/* && \
# Upgrade buggy yum:
yum -d1 -y install yum-plugin-ovl || true && \
yum -d1 -y update yum && \
# Clean (purge) the repo cache
yum -d1 -y clean all && rm -rf /var/cache/yum/* && \
# Purge logs
rm -rf /var/log/*

# Clean (purge) the repo cache
RUN yum -d1 -y clean all && \
# Update all packages
yum -d1 -y update && \
# Install init scripts
yum -d1 -y install initscripts && \
# Clean (purge) the repo cache
yum -d1 -y clean all

# Disable all services
RUN rm /etc/rc.d/rc*.d/*

# Disable ttys
RUN mv /etc/init/serial.conf /etc/init/serial.conf.disabled && \
mv /etc/init/tty.conf /etc/init/tty.conf.disabled && \
mv /etc/init/start-ttys.conf /etc/init/start-ttys.conf.disabled

# Start via init
CMD ["/sbin/init"]

# Image metadata
LABEL org.label-schema.vendor="MesaGuy" \
      org.label-schema.name="Oracle Linux 6.7 boot" \
      org.label-schema.description="Image boots Oracle Linux 6.7 via SysV init" \
      com.mesaguy.operatingsystem.eol="true"
