# Source
FROM centos:7.7.1908

# Clean (purge) the repo cache
RUN yum -d1 -y clean all && \
# Install docker OverlayFS plugin for yum:
yum -d1 -y update yum && yum -d1 -y clean all && \
# Remove troublesome packages
yum -d1 -y remove fakesystemd systemd-container systemd-container-libs  && \
# Install systemctl
yum -d1 -y install systemd systemd-libs dbus fsck.ext4 yum-plugin-ovl && \
# Update all packages
yum -d1 -y update && \
# Strip down systemd
find /lib/systemd/system/sysinit.target.wants -type l ! -name systemd-tmpfiles-setup.service -delete && \
rm -f /lib/systemd/system/multi-user.target.wants/* && \
rm -f /etc/systemd/system/*.wants/* && \
rm -f /lib/systemd/system/local-fs.target.wants/* && \
rm -f /lib/systemd/system/sockets.target.wants/*udev* && \
rm -f /lib/systemd/system/sockets.target.wants/*initctl* && \
rm -f /lib/systemd/system/basic.target.wants/* && \
rm -f /lib/systemd/system/anaconda.target.wants/* && \
# Clean (purge) the repo cache
yum -d1 -y clean all && rm -rf /var/cache/yum/* && \
# Purge logs
rm -rf /var/log/* /var/run/log/journal

# Without this, init won't start the enabled services. Starting the services
# fails with one of:
#     Failed to get D-Bus connection: Operation not permitted
#     System has not been booted with systemd as init system (PID 1). Can't operate.
#     Failed to connect to bus: No such file or directory
VOLUME [ "/sys/fs/cgroup", "/run" ]

# Start via systemd
CMD ["/usr/lib/systemd/systemd"]

# Image metadata
LABEL org.label-schema.vendor="Mesaguy" \
      org.label-schema.name="CentOS Linux 7 with latest patches boot" \
      org.label-schema.description="Image boots CentOS Linux 7 with latest patches via systemd" \
      com.mesaguy.operatingsystem.eol="false"
