FROM mesaguy/ubuntu-18.04-boot-x86_64:latest

# Update repo definitions
RUN apt update && \
# Install sudo and openssh for kitchen
apt install -y openssh-server sudo && \
# Clean (purge) the repo cache
apt-get clean && \
rm -rf /var/lib/apt/lists/* && \
# Purge logs
rm -rf /var/log/*

# Adjust sshd defaults per kitchen's needs
RUN test -f /usr/lib/openssh/sftp-server && \
printf "Subsystem sftp /usr/lib/openssh/sftp-server\nUseDNS no\nUsePAM no\nPasswordAuthentication yes\nUsePrivilegeSeparation no\n" > /etc/ssh/sshd_config && \
# Start SSH on boot
systemctl enable ssh.service && \
# Add 'kitchen' user
if ! getent passwd kitchen; then useradd -d /home/kitchen -m -s /bin/bash -p '*' kitchen; fi && \
# Allow unlimited sudo privileges to 'kitchen' user
echo "kitchen ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers && echo "Defaults !requiretty" >> /etc/sudoers && \
# Make 'kitchen' user's ~/.ssh directory
mkdir -m 0700 -p /home/kitchen/.ssh && chown -R kitchen:kitchen /home/kitchen/.ssh

# Expose SSH
EXPOSE 22

# Image metadata
LABEL org.label-schema.vendor="MesaGuy" \
      org.label-schema.name="Ubuntu Linux 18.04 (Bionic Beaver) kitchen-base" \
      org.label-schema.description="Image boots Ubuntu Linux 18.04 (Bionic Beaver) via systemd configured for kitchen testing" \
      com.mesaguy.operatingsystem.eol="false"
