FROM mesaguy/amazonlinux-2-boot-x86_64:latest

# Clean (purge) the repo cache
RUN yum -d1 -y clean all && \
# Install sudo and openssh for kitchen
yum install -y openssh-server sudo && \
# Clean (purge) the repo cache
yum -d1 -y clean all && rm -rf /var/cache/yum/* && \
# Purge logs
rm -rf /var/log/*

# Adjust sshd defaults per kitchen's needs
RUN test -f /usr/libexec/openssh/sftp-server && \
printf "Subsystem sftp /usr/libexec/openssh/sftp-server\nUseDNS no\nUsePAM no\nPasswordAuthentication yes\nUsePrivilegeSeparation no\n" > /etc/ssh/sshd_config && \
# Start SSH on boot
systemctl enable sshd.service && \
# Add 'kitchen' user
if ! getent passwd kitchen; then useradd -d /home/kitchen -m -s /bin/bash -p '*' kitchen; fi && \
# Allow unlimited sudo privileges to 'kitchen' user
echo "kitchen ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers && echo "Defaults !requiretty" >> /etc/sudoers && \
# Make 'kitchen' user's ~/.ssh directory
mkdir -m 0700 -p /home/kitchen/.ssh && chown -R kitchen:kitchen /home/kitchen/.ssh

# Expose SSH
EXPOSE 22

# Image metadata
LABEL org.label-schema.vendor="MesaGuy" \
      org.label-schema.name="Amazon Linux v2 kitchen-base" \
      org.label-schema.description="Image boots Amazon Linux v2 via systemd configured for kitchen testing" \
      com.mesaguy.operatingsystem.eol="false"
