FROM mesaguy/opensuse-42.2-boot-x86_64:latest

# Install sudo and openssh for kitchen
RUN zypper --non-interactive install openssh sudo && \
# Clean (purge) the repo cache
zypper --non-interactive clean --all && \
# Purge logs
rm -rf /var/log/* /var/run/log/journal

# Adjust sshd defaults per kitchen's needs
RUN test -f /usr/lib/ssh/sftp-server && \
printf "Subsystem sftp /usr/lib/ssh/sftp-server\nUseDNS no\nUsePAM no\nPasswordAuthentication yes\nUsePrivilegeSeparation no\n" > /etc/ssh/sshd_config && \
# Start SSH on boot
systemctl enable sshd.service && \
# Add 'kitchen' user
if ! getent passwd kitchen; then useradd -d /home/kitchen -U -m -s /bin/bash -p '*' kitchen; fi && \
# Allow unlimited sudo privileges to 'kitchen' user
echo "kitchen ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers && echo "Defaults !requiretty" >> /etc/sudoers && \
# Make 'kitchen' user's ~/.ssh directory
mkdir -m 0700 -p /home/kitchen/.ssh && chown -R kitchen:kitchen /home/kitchen/.ssh
# Copy Kitchen SSH key into environment
ARG HOME
COPY --chown=kitchen:kitchen kitchen_id_rsa.pub /home/kitchen/.ssh/authorized_keys

# Expose SSH
EXPOSE 22

# Image metadata
LABEL org.label-schema.vendor="MesaGuy" \
      org.label-schema.name="OpenSUSE Linux 42.2 kitchen-base" \
      org.label-schema.description="Image boots OpenSUSE Linux 42.2 via systemd configured for kitchen testing" \
      com.mesaguy.operatingsystem.eol="true"
