FROM mesaguy/ubuntu-14.04-kitchen-base-x86_64:latest

# Update repo definitions
RUN apt update && \
# Install puppet for kitchen
apt install -y puppet && \
# Clean (purge) the repo cache
apt-get clean && \
rm -rf /var/lib/apt/lists/* && \
# Purge logs
rm -rf /var/log/*

# Image metadata
LABEL org.label-schema.vendor="MesaGuy" \
      org.label-schema.name="Ubuntu Linux 14.04 (Trusty Tahr) kitchen-puppet" \
      org.label-schema.description="Image boots Ubuntu Linux 14.04 (Trusty Tahr) via Upstart configured for kitchen puppet testing" \
      com.mesaguy.operatingsystem.eol="false"
