FROM mesaguy/fedora-27-kitchen-base-x86_64:latest

# Clean (purge) the repo cache
RUN yum -d1 -y clean all && \
# Install puppet for kitchen
yum install -y puppet && \
# Clean (purge) the repo cache
yum -d1 -y clean all && rm -rf /var/cache/yum/* && \
# Purge logs
rm -rf /var/log/* /var/run/log/journal

# Image metadata
LABEL org.label-schema.vendor="MesaGuy" \
      org.label-schema.name="Fedora Linux 27 kitchen-puppet" \
      org.label-schema.description="Image boots Fedora Linux 27 via systemd configured for kitchen puppet testing" \
      com.mesaguy.operatingsystem.eol="true"
