FROM mesaguy/debian-7-kitchen-base-x86_64:latest

# Update repo definitions
RUN apt-get update && \
# Install puppet for kitchen
apt-get install -y puppet && \
# Clean (purge) the repo cache
apt-get clean && \
rm -rf /var/lib/apt/lists/* && \
# Purge logs
rm -rf /var/log/*

# Image metadata
LABEL org.label-schema.vendor="MesaGuy" \
      org.label-schema.name="Debian Linux 7 (Wheezy) kitchen-puppet" \
      org.label-schema.description="Image boots Debian Linux 7 (Wheezy) via Upstart configured for kitchen puppet testing" \
      com.mesaguy.operatingsystem.eol="false"
