FROM mesaguy/alpine-2.6-kitchen-base-x86_64:latest

# Update repository information
RUN apk update && \
# Install puppet prerequisites
apk add less ruby-gems && \
# Install puppet for kitchen
gem install puppet --no-rdoc --no-ri --source http://rubygems.org && \
# Remove caches
rm -f /var/cache/apk/* && \
# Purge logs
rm -rf /var/log/*

# Image metadata
LABEL org.label-schema.vendor="MesaGuy" \
      org.label-schema.name="Alpine Linux 2.6 kitchen-puppet" \
      org.label-schema.description="Image boots Alpine Linux 2.6 via OpenRC configured for kitchen puppet testing" \
      com.mesaguy.operatingsystem.eol="true"
