FROM mesaguy/amazonlinux-1-kitchen-base-x86_64:latest

# Clean (purge) the repo cache
RUN yum -d1 -y clean all && \
# Install puppet for kitchen
yum install -y puppet && \
# Clean (purge) the repo cache
yum -d1 -y clean all && rm -rf /var/cache/yum/* && \
# Purge logs
rm -rf /var/log/*

# Image metadata
LABEL org.label-schema.vendor="MesaGuy" \
      org.label-schema.name="Amazon Linux v1 kitchen-puppet" \
      org.label-schema.description="Image boots Amazon Linux v1 via SysV init configured for kitchen puppet testing" \
      com.mesaguy.operatingsystem.eol="false"
