FROM mesaguy/oraclelinux-6.9-kitchen-base-x86_64:latest

# Clean (purge) the repo cache
RUN yum -d1 -y clean all && \
# Install puppet yum repo
rpm -Uvh https://yum.puppet.com/puppet5/puppet5-release-el-6.noarch.rpm && \
# Install puppet for kitchen
yum install -y puppet-agent && \
# Clean (purge) the repo cache
yum -d1 -y clean all && rm -rf /var/cache/yum/* && \
# Purge logs
rm -rf /var/log/*

# Image metadata
LABEL org.label-schema.vendor="MesaGuy" \
      org.label-schema.name="Oracle Linux Linux 6.9 kitchen-puppet" \
      org.label-schema.description="Image boots Oracle Linux Linux 6.9 via SysV init configured for kitchen puppet testing" \
      com.mesaguy.operatingsystem.eol="false"
