FROM mesaguy/opensuse-tumbleweed-kitchen-base-x86_64:latest

# Install puppet repository
RUN zypper --non-interactive --no-gpg-checks install --no-confirm http://yum.puppet.com/puppet5/puppet5-release-sles-12.noarch.rpm && \
# Install puppet for kitchen
zypper --gpg-auto-import-keys --non-interactive install --no-confirm puppet-agent && \
# Clean (purge) the repo cache
zypper --non-interactive clean --all && \
# Purge logs
rm -rf /var/log/* /var/run/log/journal

# Image metadata
LABEL org.label-schema.vendor="MesaGuy" \
      org.label-schema.name="OpenSUSE Linux tumbleweed kitchen-puppet" \
      org.label-schema.description="Image boots OpenSUSE Linux tumbleweed via systemd configured for kitchen puppet testing" \
      com.mesaguy.operatingsystem.eol="true"
